# Generated by Django 5.0.6 on 2024-07-02 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('subreddits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subreddit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subreddits.subreddit'),
        ),
    ]
