# Generated by Django 5.0.6 on 2024-07-02 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subreddits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_subreddits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subreddit',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed_subreddits', to=settings.AUTH_USER_MODEL),
        ),
    ]
